//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebuggingConsole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DebuggingConsole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rect 1x1
        ///rotate row y=0 by 5
        ///rect 1x1
        ///rotate row y=0 by 6
        ///rect 1x1
        ///rotate row y=0 by 5
        ///rect 1x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 5
        ///rect 2x1
        ///rotate row y=0 by 2
        ///rect 1x1
        ///rotate row y=0 by 4
        ///rect 1x1
        ///rotate row y=0 by 3
        ///rect 2x1
        ///rotate row y=0 by 7
        ///rect 3x1
        ///rotate row y=0 by 3
        ///rect 1x1
        ///rotate row y=0 by 3
        ///rect 1x2
        ///rotate row y=1 by 13
        ///rotate column x=0 by 1
        ///rect 2x1
        ///rotate row y=0 by 5
        ///rotate column x=0 by 1
        ///rect 3x1
        ///rotate row y=0 by 18
        ///rotate column x=13 by 1
        ///rot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day8_Input {
            get {
                return ResourceManager.GetString("Day8_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (8x10)SBTLHXZP(141x10)(20x4)PSFDROQLSZCXJYTATIBY(2x9)NN(60x14)(3x15)WUO(2x13)WF(10x14)KRXBNHFEGQ(20x4)SWJUMHNRCRJUPDVFAKMI(35x8)(3x14)VZB(8x15)SWKZSEFU(7x1)FZTLTXZ(152x12)(59x6)(1x14)L(13x7)RYXYIAVOQLUDZ(9x13)RJEZMXTNT(1x8)J(7x5)YNAMBOU(1x4)M(65x10)(6x9)FZGSZU(20x15)JOUTNIFMADHRELAZAZXB(4x4)KDHA(12x7)VFVYZLBLKRGG(3x15)SWDGEUSLFVHBFOQCIQFDID(7506x15)(3157x7)(102x1)(95x15)(20x3)(2x6)OJ(7x12)WANSMOE(37x2)(12x2)(6x13)GFVIEP(12x11)XJNOGCDLPZFK(10x6)NZJQDFALQG(4x11)CIRV(527x9)(147x1)(28x7)(22x1)NUVOZARNIUATLYTIIB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day9_Input {
            get {
                return ResourceManager.GetString("Day9_Input", resourceCulture);
            }
        }
    }
}
